server:
  port: 8888

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

lingframe:
  enabled: true
  dev-mode: true
  plugin-home: plugins
  plugin-roots:
    - lingframe-examples/lingframe-example-plugin-order
    - lingframe-examples/lingframe-example-plugin-user

